<?php

namespace monolitum\frontend\component;

use monolitum\backend\params\Path;
use monolitum\backend\resources\Request_ResResolver;
use monolitum\backend\resources\ResResolver;
use monolitum\core\Monolitum;
use monolitum\frontend\Head;
use monolitum\frontend\html\HtmlElement;
use monolitum\frontend\Renderable;
use monolitum\frontend\Rendered;

class IconLink extends Head
{

    private ResResolver $resResolver;

    /**
     * @param Path $path
     * @param $builder
     */
    public function __construct(public readonly Path $path, $builder = null)
    {
        parent::__construct($builder);
    }

    protected function onBuild(): void
    {
        $active = new Request_ResResolver($this->path);
        Monolitum::getInstance()->push($active);
        $this->resResolver = $active->getResResolver();
        parent::onBuild(); // TODO: Change the autogenerated stub
    }

    public function render(): Renderable|array|null
    {
        $link = new HtmlElement("link");
        $link->setAttribute("rel", "icon");
        $link->setAttribute("href", $this->resResolver->resolve());

        return Rendered::of($link);
    }

}
