<?php

namespace monolitum\frontend\component;

use monolitum\backend\params\Path;
use monolitum\backend\resources\Request_ResResolver;
use monolitum\backend\resources\ResResolver;
use monolitum\core\Monolitum;
use monolitum\frontend\html\HtmlElement;
use monolitum\frontend\HtmlElementNode;
use monolitum\frontend\Renderable;

class Img extends HtmlElementNode
{

    private ?Path $source = null;

    private ?ResResolver $sourceResolver = null;

    public function __construct($builder = null)
    {
        parent::__construct(new HtmlElement("img"), $builder);
    }

    /**
     * TODO svg
     * @param Path $path
     */
    public function setSource(Path $path): void
    {
        $this->source = $path;
    }

    protected function onAfterBuild(): void
    {
        if($this->source){
            $active = new Request_ResResolver($this->source);
            Monolitum::getInstance()->push($active);
            $this->sourceResolver = $active->getResResolver();
        }

        parent::onAfterBuild();
    }

    public function render(): Renderable|array|null
    {
        $img = $this->getElement();

        if($this->sourceResolver){
            $img->setAttribute("src", $this->sourceResolver->resolve());
        }

        return parent::render(); // TODO: Change the autogenerated stub
    }

}
