<?php

namespace monolitum\backend\resources;

use Closure;
use Exception;
use monolitum\backend\params\Path;
use monolitum\core\MNode;
use monolitum\core\MObject;

class FileDownloaderManager extends MNode
{

    private Path $filePath;

    private string|false|null $fileMime;

//    private string|false $fileContents;

    private ?string $fileName = null;

    private int|false $fileLastModified;

    private string $fileLastModifiedString;

    private bool $notModifiedFlag = false;

    private ?StdoutFileWriter $fileWriter = null;

    public function __construct(?Closure $builder = null)
    {
        parent::__construct($builder);
    }

    public function doAcceptChild(MObject $object): bool
    {
        if($object instanceof Request_DownloadFile){
            $this->filePath = $object->filePath;
            $this->fileName = $object->filePath->writePath(false);
            $this->fileMime = $object->mimeType;
            $this->fileWriter = $object->fileWriter;
            return true;
        }
        return parent::doAcceptChild($object); // TODO: Change the autogenerated stub
    }

    protected function onAfterBuild(): void
    {

        if($this->fileName !== null) {

            try {

                if ($this->fileMime === null)
                    $this->fileMime = mime_content_type($this->fileName);

                $this->fileLastModified = filemtime($this->fileName);

                if ($this->fileLastModified == null)
                    throw new ResourceNotFoundPanic("Resource not found.");

                $this->fileLastModifiedString = gmdate('D, d M Y H:i:s ', $this->fileLastModified) . 'GMT';

                if (isset($_SERVER['HTTP_IF_MODIFIED_SINCE'])) {
                    //echo 'set modified header';
                    if (intval($this->fileLastModified) >= intval(strtotime($_SERVER['HTTP_IF_MODIFIED_SINCE']))) {
                        $this->notModifiedFlag = true;
                    }
                }

            } catch (Exception $e) {
                throw new ResourceNotFoundPanic("Exception.");
            }
        }

        parent::onAfterBuild();
    }

    public function doExecute(): void
    {
        if($this->fileName !== null) {

            $etag = md5($this->fileLastModified);

            header("Last-Modified: $this->fileLastModifiedString");
            header("ETag: \"$etag\"");

            // Expires must be set, because browser flashes when a CSS is requested, and it's loaded after HTML.
            $expires = gmdate('D, d M Y H:i:s ', time() + 3600 * 24) . 'GMT';
            header("Expires: $expires");

            if ($this->notModifiedFlag) {
                header('HTTP/1.1 304 Not Modified');
                return;
            }

            if ($this->fileMime) {
                header('Content-Type: ' . $this->fileMime);
            }

            $this->fileWriter->write($this, $this->filePath, $this->fileMime);

            //echo $this->fileContents;

//        $rewriter = $this->fileWriter->getRewriter($this->filePath);
//
//        if($rewriter === null){
//            readfile($this->fileName);
//        }else if($this->fileWriter->readLineByLine()){
//
//            $handle = fopen($this->fileName, "r");
//            if ($handle) {
//                while (($line = fgets($handle)) !== false) {
//                    // process the line read.
//                    echo $rewriter($line);
//                }
//
//                fclose($handle);
//            }
//
//        }else{
//            echo $rewriter(file_get_contents($this->fileName));
//        }

        }

        parent::doExecute();
    }

}
