<?php

namespace monolitum\bootstrap\component;

use Closure;
use monolitum\bootstrap\values\BSColor;
use monolitum\frontend\component\AbstractTextNode;
use monolitum\frontend\html\HtmlElement;

class Alert extends AbstractTextNode
{

    private ?BSColor $color = null;

    public function __construct(?Closure $builder = null)
    {
        parent::__construct(new HtmlElement("div"), $builder);
    }

    /**
     * @param BSColor $color
     */
    public function setAlertColor(BSColor $color): self
    {
        $this->color = $color;
        return $this;
    }

    protected function onAfterBuild(): void
    {
        $this->addClass("alert");

        if($this->color !== null){
            $this->addClass("alert-" . $this->color->getValue());
        }

        parent::onAfterBuild(); // TODO: Change the autogenerated stub
    }

}
