<?php

namespace monolitum\frontend;

use monolitum\core\MNode;
use monolitum\core\MObject;
use monolitum\core\panic\DevPanic;
use monolitum\core\panic\NodePanicRouter;
use monolitum\frontend\html\HtmlElement;
use monolitum\i18n\TS;

abstract class Renderable_Node extends MNode {

    public function __construct($builder = null)
    {
        parent::__construct($builder);
    }

    public function doAcceptChild(MObject $object): bool
    {
        if($object instanceof NodePanicRouter){
            return false;
        }else if($object instanceof Renderable){
            $this->buildAndAppendChild($object);
            return true;
        }
        return parent::doAcceptChild($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param string|array|Renderable|Renderable_Node|TS|null $active
     * @param int|null $idx
     * @return $this
     */
    public function append(Renderable_Node|Renderable|string|TS|array|null $active, ?int $idx=null): self
    {
        // Ignore null values
        if($active !== null){
            $this->buildAndInsertChild($this->buildRenderable($active), $idx);
        }
        return $this;
    }

    public function buildRenderable(Renderable_Node|Renderable|string|TS|array $renderable): Renderable_Node|Renderable
    {
        if ($renderable instanceof Renderable_Node) {
            return $renderable;
        }else if(is_array($renderable)){
            return Rendered::of($renderable);
        }else if(is_string($renderable)){
            return Rendered::of($renderable);
        }else if($renderable instanceof TS){
            return Rendered::of(TS::unwrapAuto($renderable));
        }else {
            return $renderable;
        }
    }

    public function buildAndAppendNewReference(): Reference
    {
        $ref = new Reference();
        $this->buildAndAppendChild($ref);
        return $ref;
    }

    function onNotReceived()
    {
        throw new DevPanic("Component " . $this . " was not received by any parent when added.");
    }

    public function render(): Renderable|array|null
    {
        return $this->renderChildren();
    }

    /**
     * @return Renderable|array|null
     */
    public function renderChildren(): Renderable|array|null
    {
        return Renderable_Node::valueToRenderable($this->getChildren());
    }

    public static function valueToRenderable(mixed $value): Renderable|array|null
    {
        if(is_array($value)){
            $rendered = [];
            foreach ($value as $child) {
                if($child instanceof Renderable_Node) {
                    $rendered[] = $child->render();
                }else if($child instanceof Renderable){
                    $rendered[] = $child;
                }else if($child instanceof MNode){
                    foreach ($child->getChildren() as $child2) {
                        self::renderNonRenderableNode($child2, $rendered);
                    }
                }
            }
            return $rendered;
        }else{
            if($value instanceof Renderable_Node) {
                return $value->render();
            }else if($value instanceof Renderable){
                return $value;
            }else if($value instanceof MNode){
                $rendered = [];
                foreach ($value->getChildren() as $child) {
                    self::renderNonRenderableNode($child, $rendered);
                }
                return $rendered;
            }
        }
        return null;

    }

    public static function renderNonRenderableNode(MObject $value, array &$currentRenderedArray): void
    {
        if($value instanceof Renderable_Node) {
            $currentRenderedArray[] = $value->render();
        }else if($value instanceof Renderable){
            $currentRenderedArray[] = $value;
        }else if($value instanceof MNode){
            foreach ($value->getChildren() as $child) {
                self::renderNonRenderableNode($child, $currentRenderedArray);
            }
        }

    }

    /**
     * @param array|Renderable|Renderable_Node|null $rendered
     * @param HtmlElement $element
     * @return void
     */
    public static function renderRenderedTo(array|Renderable_Node|Renderable|null $rendered, HtmlElement $element): void
    {

        if(is_array($rendered)){
            foreach ($rendered as $rendered2) {
                Renderable_Node::renderRenderedTo($rendered2, $element);
            }
        }else if($rendered instanceof Renderable_Node){
            Renderable_Node::renderRenderedTo($rendered->render(), $element);
        }else if($rendered instanceof Renderable) {
            $rendered->renderTo($element);
        }

    }


}
