<?php

namespace monolitum\auth;

use Closure;
use monolitum\auth\roles\RolesController;
use monolitum\auth\users\UsersController;
use monolitum\core\Find;
use monolitum\core\MNode;
use monolitum\core\security\CSRFTokenProvider;
use monolitum\model\Entity;

class AuthManager extends MNode implements CSRFTokenProvider
{

    private ?UsersController $usersController = null;
    private ?RolesController $rolesController = null;
    private ?Session $session = null;

    public function __construct(?Closure $builder = null)
    {
        parent::__construct($builder);
    }

    /**
     * @param UsersController $usersController
     */
    public function setUsersController(UsersController $usersController): void
    {
        $this->usersController = $usersController;
        $this->usersController->install($this);
    }

    /**
     * @param RolesController $rolesController
     */
    public function setRolesController(RolesController $rolesController): void
    {
        $this->rolesController = $rolesController;
        $this->rolesController->install($this);
    }

    protected function onBuild(): void
    {
        parent::onBuild();
    }

    protected function onAfterBuild(): void
    {
        parent::onAfterBuild(); // TODO: Change the autogenerated stub
    }

//    public function addRoleModel(RoleModel $roleModel): void
//    {
//        $roleModel->install($this);
//        $this->roleModels[$roleModel->clazz] = $roleModel;
//    }
//
//    public function permission(string $permissionId, Closure $predicate): void
//    {
//        $this->permissions[$permissionId] = $predicate;
//    }
//
//    public function requireRole(string $roleClass): Entity {
//        $user = $this->requireLogin();
//
//        if(!isset($this->roleModels[$roleClass])){
//            throw new AuthPanic_NoPermissions();
//        }
//        /** @var RoleModel $roleModel */
//        $roleModel = $this->roleModels[$roleClass];
//
//        $role = Query::newQuery($roleModel->getModel())
//            ->filter([
//                $roleModel->getAttrUserId()->getId() => $user->getValue($this->userId),
//                $roleModel->getAttrEnabled()->getId() => true
//            ])
//            ->execute($this->managerDB)
//            ->firstAndClose();
//
//        if($role == null){
//            throw new AuthPanic_NoPermissions();
//        }
//
//        return $role;
//    }

    public function changePassword(Entity $user, string $plainPassword): bool
    {
        if($this->usersController == null){
            throw new AuthPanic("Login failed: UsersController is not set!");
        }

        return $this->usersController->changePassword($user, $plainPassword);

    }

    /**
     * @return void
     */
    private function sessionStartOrFail(): void
    {
        if (!session_id()){
            $result = session_start();
            if(!$result)
                throw new AuthPanic("Panic: Session not working!");
        }
    }

    public function logIn(string $username, string $password): bool
    {

        if($this->usersController == null){
            throw new AuthPanic("Login failed: UsersController is not set!");
        }

        $this->session = $this->usersController->loginByCredentials($username, $password);

        if($this->session != null){
            $this->sessionStartOrFail();

            $_SESSION['session_string'] = $this->usersController->getSessionString($this->session);

            return true;
        }

        return false;
    }

    private function requireLogin(): Session
    {
        if($this->session == null){

            if(session_id() === null)
                throw new AuthPanic_NotLoggedIn();

            session_start();

            if(!isset($_SESSION['session_string']) || $_SESSION['session_string'] == null)
                throw new AuthPanic_NotLoggedIn();

            if($this->usersController == null){
                throw new AuthPanic("Login failed: UsersController is not set!");
            }

            $this->session = $this->usersController->recoverSession($_SESSION['session_string']);

            if($this->session == null){
                $_SESSION['session_string'] = null;
            }

        }

        if($this->session != null){
            return $this->session;
        }

        throw new AuthPanic_NotLoggedIn();
    }

    public function isCSRFSystemAvailable(): bool
    {
        // We can send the session cookie at any time, so we are available
        return true;
    }

    public function getCurrentCSRFToken(): string
    {

        $this->sessionStartOrFail();

        if(!isset($_SESSION['csrf_token']) || $_SESSION['csrf_token'] == null){
            $token = bin2hex(openssl_random_pseudo_bytes(32));
            if(!$token)
                throw new AuthPanic("Panic: RNG not working!");
            $_SESSION['csrf_token'] = $token;
        }

        return $_SESSION['csrf_token'];

    }

    public function requirePermission(string $permissionKey): void
    {
        if(!$this->hasPermission($permissionKey)){
            throw new AuthPanic_NoPermissions();
        }
    }

    public function hasPermission(string $permissionKey): bool
    {
        $session = $this->requireLogin();

        $hasPermission = false;
        if($this->rolesController !== null){
            $hasPermission = $this->rolesController->hasPermission($session, $permissionKey);
        }

        if(!$hasPermission){
            if($this->usersController != null){
                $hasPermission = $this->usersController->hasPermission($session, $permissionKey);
            }
        }

        return $hasPermission;
    }

    private function logout(): void
    {
        if(session_id()){
            session_destroy();
        }

        $this->session = null;
//            session_start();
//        $_SESSION['username'] = null;

    }

    private function isLoggedIn(): bool
    {
        if(!session_id())
            return false;

        if(!isset($_SESSION['session_string']) || $_SESSION['session_string'] == null)
            return false;

        return true;
    }

    public static function pushRequireLogin(): Session
    {
        /** @var AuthManager $manager */
        $manager = Find::pushAndGet(AuthManager::class);
        return $manager->requireLogin();
    }

    /**
     * @param string $permissionId
     * @return void
     */
    public static function pushRequirePermission(string $permissionId): void
    {
        /** @var AuthManager $manager */
        $manager = Find::pushAndGet(AuthManager::class);
        $manager->requirePermission($permissionId);
    }

    /**
     * @param string $permissionId
     * @return bool
     */
    public static function pushHasPermission(string $permissionId): bool
    {
        /** @var AuthManager $manager */
        $manager = Find::pushAndGet(AuthManager::class);
        return $manager->hasPermission($permissionId);
    }

    public static function pushLogout(): void
    {
        /** @var AuthManager $manager */
        $manager = Find::pushAndGet(AuthManager::class);
        $manager->logout();
    }

    public static function pushIsLoggedIn(): bool
    {
        /** @var AuthManager $manager */
        $manager = Find::pushAndGet(AuthManager::class);
        return $manager->isLoggedIn();
    }

}
